version: 2
jobs:
  build_and_test:
    docker:
      # specify the version you desire here
      - image: mattconway55/hundred-builder:0.0.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm test

  server_deploy:
    docker:
      - image: mattconway55/hundred-builder:0.0.1 
    steps:
      - checkout
      - run: |
          echo $GOOGLE_AUTH | base64 --decode > ${HOME}/worker.json
          gcloud auth activate-service-account --key-file=${HOME}/worker.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud builds submit --tag gcr.io/${GOOGLE_PROJECT_ID}/hundred-game-backend
          gcloud beta run services add-iam-policy-binding --region=us-central1 --member=allUsers --role=roles/run.invoker hundred-game-backend
          gcloud beta run deploy --image gcr.io/${GOOGLE_PROJECT_ID}/hundred-game-backend --platform managed --region us-central1 --allow-unauthenticated

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - server_deploy:
          requires:
            - build_and_test