version: 2
jobs:
  build_and_test:
    docker:
      # specify the version you desire here
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm test

  server_deploy:
    machine: true
    steps:
      - checkout
      - run: |
          echo $GOOGLE_AUTH | base64 --decode > ${HOME}/worker.json
          sudo gcloud --quiet components update
          gcloud auth activate-service-account --key-file=${HOME}/worker.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud builds submit --tag gcr.io/${GOOGLE_PROJECT_ID}/hundred-game-backend
          gcloud beta run deploy --image gcr.io/${GOOGLE_PROJECT_ID}/hundred-game-backend

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - server_deploy:
          requires:
            - build_and_test