name: GCP Deploy

on: 
  push:
    branches:
      - master

jobs:

  auth:
    runs-on: ubuntu-latest
    steps:
      - name: GCP Authenticate
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
  build:
    runs-on: ubuntu-latest
    needs: auth
    steps:
      - name: GCP Build Container
        env:
          CLOUDSDK_CORE_PROJECT: second-scion-236722
        with:
          args: builds submit --tag gcr.io/second-scion-236722/hundred-game-backend
        uses: actions/gcloud/cli@master
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: GCP Deploy Revision
        env:
          CLOUDSDK_CORE_PROJECT: second-scion-236722
        with:
          args: beta run deploy --image gcr.io/second-scion-236722/hundred-game-backend
        uses: actions/gcloud/cli@master
